# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: squirtlesquad
      POSTGRES_DB: pkdb
    ports:
      - 5464:5464